name: Testing

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing1

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
